namespace DateDeclare
{
    using System;

    public enum EGameTipType
    {
        App_Update = 0,
        ApplyForExpCoin_CoinOver = 11,
        ApplyForExpCoin_Faild = 9,
        ApplyForExpCoin_Success = 8,
        ApplyForExpCoin_Tip = 10,
        ApplyRepeat = 60,
        Awarding_CoinAbsence = 0x38,
        Awarding_Empty = 0x36,
        Awarding_Error = 0x37,
        Awarding_Faild = 0x3b,
        Awarding_PassworError = 0x39,
        Awarding_ReplySuccess = 0x49,
        Awarding_Success = 0x3a,
        AwardingBeClosed = 0x3e,
        ChangeCodeSucceed = 0x48,
        CoinOverFlow = 14,
        Emial_IsDeleted = 0x2d,
        Emial_NotExit = 0x2e,
        Emial_SelectedEmpty = 0x2c,
        ForgetPwd = 40,
        Game_UnOpen = 0x35,
        Game_Update = 1,
        Game_UserIdFrozen = 15,
        GameDownloading = 0x4c,
        GameUnRunState = 12,
        GivingCoin = 20,
        HasBeDeleted = 0x13,
        HasBeLogined = 0x11,
        InteractionsPaneCloseInexorable = 0x4d,
        Interface_Faid = 50,
        Interface_Succses = 0x31,
        IsExitHall = 0x2f,
        IsExitRegister = 0x30,
        Login_IDMismatchingPwd = 2,
        Net_ConnectionError = 0x34,
        NetConnectionOff = 0x33,
        NoneTip = -1,
        OperationalVersion_ChangeCode = 0x4b,
        PassworHasBeenModified = 0x12,
        PwdInputError = 0x16,
        PwdInputError_Charcter = 0x18,
        PwdInputError_Digit = 0x17,
        PwdLengthError = 0x19,
        ReceptionistTrade = 0x2b,
        ReCharge_Error = 0x41,
        ReCharge_Faild = 0x42,
        ReCharge_ReplySuccess = 0x4a,
        ReCharge_Success = 0x40,
        Recommender_Empty = 0x44,
        Recommender_Error = 0x45,
        Recommender_NoExit = 0x43,
        Register_Faild = 5,
        Register_IDInputError = 0x1c,
        Register_IDLengthError = 0x1d,
        Register_IDNmFormatError = 0x23,
        Register_IDNumberEmpty = 0x22,
        Register_IDRepetitive = 3,
        Register_MismatchCharacter = 0x1f,
        Register_NicknameAllWhiteSpace = 0x21,
        Register_NicknameEmpty = 30,
        Register_NicknameLengthError = 0x20,
        Register_SafetyAnswerEmpty = 0x27,
        Register_SafetyProblemEmpty = 0x26,
        Register_Success = 4,
        Register_TeleNmFormatError = 0x25,
        Register_TeleNumberEmpty = 0x24,
        ReMarkInfo_Error = 0x3f,
        RepwdMismatching = 0x1a,
        ScoreLastGame = 0x47,
        ScoreOverflow = 70,
        ServerUpdate = 0x10,
        Supplement_Faild = 7,
        Supplement_Success = 6,
        SystemError = 13,
        UpdatePwd_OldPwdEmpty = 0x29,
        UpdatePwd_OldPwdError = 0x2a,
        UserIDEmpty = 0x1b,
        UserPwdEmpty = 0x15,
        YouKe_ChangeCode = 0x3d
    }
}

